version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    env_file:
      - .env
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_LOGIN}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - /db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  api:
    build: ./
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: "${NODE_ENV}"
      DB_HOST: db
      DB_LOGIN: "${DB_LOGIN}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      REDIS_HOST: redis
      REDIS_PORT: "${REDIS_PORT}"
      REDIS_DB: "${REDIS_DB}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_USERNAME: "${REDIS_USERNAME}"
      TYPEORM_MIGRATIONS_TABLE_NAME: "${TYPEORM_MIGRATIONS_TABLE_NAME}"
      POOL_SIZE: "${POOL_SIZE}"
volumes:
  db:
    driver: local
  redis_data:
